image: python:3.10

pipelines:
  default:
    - step:
        name: Build and push Docker images
        script:
          - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
          - docker build -t bellout/microteksapi .
          - docker push bellout/microteksapi
        services:
          - docker
    - step:
        name: Deploy to DigitalOcean
        script:
          - pipe: atlassian/ssh-run:0.3.0
            variables:
              SERVER: $DIGITALOCEAN_DROPLET_API_IP
              SSH_USER: '$SSH_USER'
              SERVER_PORT: '80'
              COMMAND: >
                echo "Current Working Directory on Droplet: " &&
                pwd &&
                echo "Listing Files in Working Directory on Droplet:" &&
                ls -l &&
                chmod +x cleanbash.sh &&
                bash ./cleanbash.sh
          - pipe: atlassian/ssh-run:0.2.8
            variables:
              SERVER: $DIGITALOCEAN_DROPLET_API_IP
              SSH_USER: '$SSH_USER'
              SERVER_PORT: '80'
              COMMAND: 'docker run --restart unless-stopped  --detach --publish 80:80 bellout/microteksapi '
        services:
          - docker
